### ISSUE TITLE
Error with ternary in if/else block

### ISSUE THREAD

**Issue by Hinaichigo** [OpenDreamProject/OpenDream#705] opened 2022-05-30 14:44 UTC
While compiling /vg/station, the following error occurs:
`Error at code\game\machinery\doors\airlock.dm:1153:9: Expected ':'`
```
1151 if(M.client)
1152 	density ? open(1):close(1)
1153 else if(density)
1154	open(1)
```

**Comment by ike709** [comment] 2022-05-30 17:15
Dupe of one of the other ternary issues IIRC

**Comment by wixoaGit** [comment] 2022-05-30 17:42
> Dupe of one of the other ternary issues IIRC

There's #416 which I think is an issue with parsing a `"String":property` expression, and this looks to be an issue with parsing a ternary with proc calls in both the `b` and `c` expressions.

**Comment by Hinaichigo** [comment] 2022-09-22 00:27
Also the error in the above comment occurs within a for() loop:
```
/swapmap/proc/ConsiderRegion(X1,Y1,X2,Y2,Z1,Z2)
	while(1)
		var/nextz=0
		var/swapmap/M
		for(M in swapmaps_loaded)
			if(M.z2<Z1 || (Z2 && M.z1>Z2) || M.z1>=Z1+z2 ||\
				M.x1>X2 || M.x2<X1 || M.x1>=X1+x2 ||\
				M.y1>Y2 || M.y2<Y1 || M.y1>=Y1+y2)
				continue
			// look for sub-regions with a defined ceiling
			var/nz2=Z2?(Z2):Z1+z2-1+M.z2-M.z1
			if(M.x1>=X1+x2)
				.=ConsiderRegion(X1,Y1,M.x1-1,Y2,Z1,nz2)
				if(.)
					return
			else if(M.x2<=X2-x2)
				.=ConsiderRegion(M.x2+1,Y1,X2,Y2,Z1,nz2)
				if(.)
					return
			if(M.y1>=Y1+y2)
				.=ConsiderRegion(X1,Y1,X2,M.y1-1,Z1,nz2)
				if(.)
					return
			else if(M.y2<=Y2-y2)
				.=ConsiderRegion(X1,M.y2+1,X2,Y2,Z1,nz2)
				if(.)
					return
			nextz=nextz?min(nextz,M.z2+1):(M.z2+1)
		if(!M)
			/* If nextz is not 0, then at some point there was an overlap that
				could not be resolved by using an area to the side */
			if(nextz)
				Z1=nextz
			if(!nextz || (Z2 && Z2-Z1+1<z2))
				return (!Z2 || Z2-Z1+1>=z2)?list(X1,Y1,Z1):null
			X1=1;X2=world.maxx
			Y1=1;Y2=world.maxy
```
So it may be that fixing #656 may fix it.

**Comment by wixoaGit** [comment] 2023-06-06 06:35
This is no longer an issue.

**Closed by wixoaGit** 2023-06-06 06:35 UTC
Labels: Compiler
