### ISSUE TITLE
Curlybrace blocks have harsher indentation requirements than BYOND

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1039] opened 2023-01-19 21:12 UTC
Valid DM that throws errors: (expected dedent)
```
new /obj{
    name = "thing"
    }
```
```
var/condition = 1
if(condition) 
{
    world.log << "stuff"
    }
```

**Comment by wixoaGit** [comment] 2023-12-21 02:10
Duplicate of #512

**Closed by wixoaGit** 2023-12-21 02:10 UTC
Labels: Compiler
