### ISSUE TITLE
When respawned, the dead HUD element appears

### ISSUE THREAD

**Issue by mudzbe** [OpenDreamProject/OpenDream#1585] opened 2023-12-31 03:49 UTC
![image](https://github.com/OpenDreamProject/OpenDream/assets/60084963/907ffb81-279c-44f7-b8d0-a3945a55528b)

I got respawned by admins after gibbed spontaneously but the dead HUD element appeared on my character
Examine shows you are alive, all controls work

On SS14 paradise test

**Comment by ike709** [comment] 2023-12-31 03:59
Presumably fixed by https://github.com/OpenDreamProject/OpenDream/pull/1565 fixing `client.images`

**Comment by ike709** [comment] 2024-10-06 20:05
Can't reproduce; presumably fixed by #1565

**Closed by ike709** 2024-10-06 20:05 UTC
