### ISSUE TITLE
JSON requires double quotes instead of single quotes

### ISSUE THREAD

**Issue by out-of-phaze** [OpenDreamProject/OpenDream#839] opened 2022-10-04 23:23 UTC
`json_decode("{'foo':1}")` is valid in BYOND DM and gives `list("foo" = 1)` but fails in OpenDream at runtime with `System.Text.Json.JsonException: ''' is an invalid start of a property name. Expected a '"'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.`

**Comment by SpaceManiac** [comment] 2022-10-23 07:09
Does `json_encode` ever produce these documents? If not, where do they come from?

**Comment by wixoaGit** [comment] 2023-04-17 18:03
This goes against the json standard. Fixing this would require writing our own (likely significantly slower) json parser. The downsides are too great and the problem is really easy to fix from the DM side.

We won't be fixing this.

**Closed by wixoaGit** 2023-04-17 18:03 UTC
Labels: wontfix, Runtime, Parity
