### ISSUE TITLE
Case Sensitivity on Resource Paths

### ISSUE THREAD

**Issue by amylizzle** [OpenDreamProject/OpenDream#1267] opened 2023-06-02 10:49 UTC
Introduced by #1242 - resource paths are case sensitive on case sensitive OS (ie, linux) when they shouldn't be. In BYOND, resource paths are case insensitive regardless of the OS.

**Comment by Insineer** [comment] 2023-06-03 16:11
Were resources with wrong-cased paths loaded by OpenDream on Linux before my fix? Or it just silently ignored them?

I've tried this with BYOND, and there are really case insensitive paths regardless of the OS. Seems like BYOND implements some specific files searching logic for Linux.

**Comment by amylizzle** [comment] 2023-06-03 19:07
Not sure but I'd guess they were ignored silently. Your fix just makes them not silent.

**Comment by wixoaGit** [comment] 2023-06-03 19:17
This was previously a runtime error (#591). #1242 just moved the error from runtime to compile-time.

**Comment by wixoaGit** [comment] 2023-06-03 19:20
Duplicate of #591

**Closed by wixoaGit** 2023-06-03 19:20 UTC
Labels: bug, Compiler
