### ISSUE TITLE
Paradise playtest: some screen elements never disappear

### ISSUE THREAD

**Issue by optimumtact** [OpenDreamProject/OpenDream#1606] opened 2024-01-02 21:22 UTC
I got into a box then popped out to scare someone, somehow this also scared me and gave us both the red exclamation alert, but it never faded either.

![image](https://github.com/OpenDreamProject/OpenDream/assets/2544323/c5033580-a551-4f64-94ab-3e0b2bb4d400)

**Comment by ike709** [comment] 2024-01-02 21:31
Are these handled by `client.images`? Possible dupe of https://github.com/OpenDreamProject/OpenDream/issues/1422

**Comment by wixoaGit** [comment] 2024-01-03 03:58
The box displays the image using `flick_overlay(I,viewing,8)`

```
/proc/remove_images_from_clients(image/I, list/show_to)
	for(var/client/C in show_to)
		C.images -= I

/proc/flick_overlay(image/I, list/show_to, duration)
	for(var/client/C in show_to)
		C.images += I
	addtimer(CALLBACK(GLOBAL_PROC, GLOBAL_PROC_REF(remove_images_from_clients), I, show_to), duration, TIMER_CLIENT_TIME)
```

Something about the timer or `remove_images_from_clients` is not working.

**Comment by optimumtact** [comment] 2024-01-04 02:39
oh update, i was wearing the pet chicken on my head at hte time I popped out of the box, not sure if that was related.

**Comment by ike709** [comment] 2024-01-22 05:43
I can't seem to reproduce this. I think the `client.images` fix fixed this?

**Comment by wixoaGit** [comment] 2024-02-12 06:18
I cannot replicate this anymore either.

**Closed by wixoaGit** 2024-02-12 06:18 UTC
